### ISSUE TITLE
Is it possible to use node-serialport?

### ISSUE THREAD

**Issue by renatop7** [angular-guru/electron-builder#1]
Hi,

I've been trying to implement an Angular 6 + Electron app that uses node-serialport (https://www.npmjs.com/package/serialport), but so far I had no luck.

What I've tried:

`npm i serialport @types/serialport --save`

app.component.ts
```
import * as SerialPort from 'serialport'

constructor(){
    SerialPort.list().then( ports => console.log(ports)).catch(err => console.log(err));
}
```

In Electron Browser Console I get this error:

`Could not find bindings.js file`

Do you think is possible to use SerialPort with this seed?

**Comment by ashh640** [comment]
Hi,

Apologies for the delayed response, I have been traveling for the last two weeks.

With this build architect you should be able to use pretty much any library that supports Electron. While I'm not sure of the exact reason perhaps this link might help you:

https://github.com/node-serialport/node-serialport/issues/1087

Hope this helps!
