### ISSUE TITLE
Specific electron builder for karma testing

### ISSUE THREAD

**Issue by ghost** [angular-guru/electron-builder#4]
First of all thanks for the builder, helped a lot.

My problem is that I run the tests on an electron window using the package `karma-electron` (https://www.npmjs.com/package/karma-electron). Due the changes on Angular using the `@angular-devkit/build-angular:karma` builder  throws an error with the`Can't resolve 'fs'` message.

Wondering if the possibility of adding a builder for the tests is contemplated.

**Comment by ashh640** [comment]
Hi, thanks for the feedback. I have added a karma builder, hopefully this will work for you in your set up. I will make an npm release hopefully later today. Thanks!

**Comment by ashh640** [comment]
New npm package should now be published

**Comment by ghost** [comment]
Thanks for the quick solution @ashh640 !
