### ISSUE TITLE
Could not find the implementation for builder @angular-guru/electron-builder:dev-server 

### ISSUE THREAD

**Issue by Sawuus** [angular-guru/electron-builder#5]
Angular CLI v8 switches default builder to the new architect and electron-builder is incompatible with @angular-devkit/build-angular": "~0.800.0"

**Comment by ashh640** [comment]
Thanks for the feedback! I'm currently travelling, I will hopefully get a fix released late next week once I return.

**Comment by SAnDAnGE** [comment]
Any feedback on this ?

**Comment by ashh640** [comment]
Just published a new version that should work with Angular 8. Apologies for the delay, the whole builder API changed with v8 so it took a bit longer than expected.
